//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Недвижимость.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class apartment_demands
    {
        public int Id { get; set; }
        public Nullable<int> idCyty { get; set; }
        public Nullable<int> idDistricts { get; set; }
        public Nullable<int> Address_House { get; set; }
        public Nullable<int> Address_Number { get; set; }
        public Nullable<decimal> MinPrice { get; set; }
        public Nullable<decimal> MaxPrice { get; set; }
        public int AgentId { get; set; }
        public int ClientId { get; set; }
        public Nullable<int> MinArea { get; set; }
        public string MaxArea { get; set; }
        public Nullable<int> MinRooms { get; set; }
        public Nullable<int> MaxRooms { get; set; }
        public Nullable<int> MinFloor { get; set; }
        public Nullable<int> MaxFloor { get; set; }
    
        public virtual agent agent { get; set; }
        public virtual City City { get; set; }
        public virtual client client { get; set; }
        public virtual district district { get; set; }
    }
}
